// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Owner;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect OwnerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OwnerDataOnDemand: @Component;
    
    private Random OwnerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Owner> OwnerDataOnDemand.data;
    
    public Owner OwnerDataOnDemand.getNewTransientOwner(int index) {
        com.springsource.petclinic.domain.Owner obj = new com.springsource.petclinic.domain.Owner();
        setFirstName(obj, index);
        setLastName(obj, index);
        setAddress(obj, index);
        setCity(obj, index);
        setTelephone(obj, index);
        setHomePage(obj, index);
        setEmail(obj, index);
        setBirthDay(obj, index);
        return obj;
    }
    
    private void OwnerDataOnDemand.setFirstName(Owner obj, int index) {
        java.lang.String firstName = "firstName_" + index;
        if (firstName.length() > 30) {
            firstName = firstName.substring(0, 30);
        }
        obj.setFirstName(firstName);
    }
    
    private void OwnerDataOnDemand.setLastName(Owner obj, int index) {
        java.lang.String lastName = "lastName_" + index;
        if (lastName.length() > 30) {
            lastName = lastName.substring(0, 30);
        }
        obj.setLastName(lastName);
    }
    
    private void OwnerDataOnDemand.setAddress(Owner obj, int index) {
        java.lang.String address = "address_" + index;
        if (address.length() > 50) {
            address = address.substring(0, 50);
        }
        obj.setAddress(address);
    }
    
    private void OwnerDataOnDemand.setCity(Owner obj, int index) {
        java.lang.String city = "city_" + index;
        if (city.length() > 30) {
            city = city.substring(0, 30);
        }
        obj.setCity(city);
    }
    
    private void OwnerDataOnDemand.setTelephone(Owner obj, int index) {
        java.lang.String telephone = "telephone_" + index;
        obj.setTelephone(telephone);
    }
    
    private void OwnerDataOnDemand.setHomePage(Owner obj, int index) {
        java.lang.String homePage = "homePage_" + index;
        if (homePage.length() > 30) {
            homePage = homePage.substring(0, 30);
        }
        obj.setHomePage(homePage);
    }
    
    private void OwnerDataOnDemand.setEmail(Owner obj, int index) {
        java.lang.String email = "email_" + index;
        if (email.length() > 30) {
            email = email.substring(0, 30);
        }
        obj.setEmail(email);
    }
    
    private void OwnerDataOnDemand.setBirthDay(Owner obj, int index) {
        java.util.Date birthDay = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setBirthDay(birthDay);
    }
    
    public Owner OwnerDataOnDemand.getSpecificOwner(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Owner obj = data.get(index);
        return Owner.findOwner(obj.getId());
    }
    
    public Owner OwnerDataOnDemand.getRandomOwner() {
        init();
        Owner obj = data.get(rnd.nextInt(data.size()));
        return Owner.findOwner(obj.getId());
    }
    
    public boolean OwnerDataOnDemand.modifyOwner(Owner obj) {
        return false;
    }
    
    public void OwnerDataOnDemand.init() {
        data = com.springsource.petclinic.domain.Owner.findOwnerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Owner' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.springsource.petclinic.domain.Owner>();
        for (int i = 0; i < 10; i++) {
            com.springsource.petclinic.domain.Owner obj = getNewTransientOwner(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
